import Home from './home/home.container';
import Browse from './browse/browse.container';
import Profile from './profile/profile.container';
import MyPath from './myPath/myPath.container';
import Quiz from './quiz/quiz.container';
import Overview from './overview/overview.container';
import Syllabus from './syllabus/syllabus.container';
import SyllabusDetail from './syllabusDetail/syllabusDetail.container';
import Authenticate from './authenticate/authenticate.container';
import NonAuthenticate from './non_authenticate/non_authenticate.container';
import ViewAll from './viewall/viewall';
import Question from './question/question.container';
import Practice from './practice/practice.container';
export {Home, Browse, Profile, Quiz, Overview, MyPath, Syllabus, SyllabusDetail, ViewAll, Authenticate, NonAuthenticate, Question, Practice};
