export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const CHANGELANGUAGE_TO_EN = 'CHANGELANGUAGE_TO_EN';
export const CHANGELANGUAGE_TO_VI = 'CHANGELANGUAGE_TO_VI';
