export const FETCH_BROWSE_PATH = 'FETCH_BROWSE_PATH';
export const FETCH_HOME_PATH = 'FETCH_HOME_PATH';

export const FETCH_PATH_SUCCESS = 'FETCH_PATH_SUCCESS';
export const FETCH_PATH_FAILED = 'FETCH_PATH_FAILED';

export const SEARCH_PATH_REQUEST = 'SEARCH_PATH_REQUEST';
export const SEARCH_PATH_SUCCESS = 'SEARCH_PATH_SUCCESS';
export const SEARCH_PATH_FAILED = 'SEARCH_PATH_FAILED';

export const FETCH_OVERVIEW_REQUEST = 'FETCH_OVERVIEW_REQUEST';
export const FETCH_OVERVIEW_SUCCESS = 'FETCH_OVERVIEW_SUCCESS';
export const FETCH_OVERVIEW_FAILED = 'FETCH_OVERVIEW_FAILED';

export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAILED = 'FETCH_COURSES_FAILED';

export const FETCH_INSTRUMENT_REQUEST = 'FETCH_INSTRUMENT_REQUEST';
export const FETCH_INSTRUMENT_SUCCESS = 'FETCH_INSTRUMENT_SUCCESS';
export const FETCH_INSTRUMENT_FAILED = 'FETCH_INSTRUMENT_FAILED';

export const FETCH_OVERALL_PROGRESS_REQUEST = 'FETCH_OVERALL_PROGRESS_REQUEST';
export const FETCH_OVERALL_PROGRESS_SUCCESS = 'FETCH_OVERALL_PROGRESS_SUCCESS';
export const FETCH_OVERALL_PROGRESS_FAILED = 'FETCH_OVERALL_PROGRESS_FAILED';

export const SUBSCRIBE_PATH_REQUEST = 'SUBSCRIBE_PATH_REQUEST';
export const SUBSCRIBE_PATH_SUCCESS = 'SUBSCRIBE_PATH_SUCCESS';
export const SUBSCRIBE_PATH_FAILED = 'SUBSCRIBE_PATH_FAILED';

export const UNSUBSCRIBE_PATH_REQUEST = 'UNSUBSCRIBE_PATH_REQUEST';
export const UNSUBSCRIBE_PATH_SUCCESS = 'UNSUBSCRIBE_PATH_SUCCESS';
export const UNSUBSCRIBE_PATH_FAILED = 'UNSUBSCRIBE_PATH_FAILED';