export const FETCH_PATH = 'FETCH_PATH';
export const FETCH_PATH_SUCCESS = 'FETCH_PATH_SUCCESS';
export const FETCH_PATH_FAILED = 'FETCH_PATH_FAILED';

export const FETCH_BROWSE_PATH = 'FETCH_BROWSE_PATH';
export const FETCH_BROWSE_PATH_SUCCESS = 'FETCH_BROWSE_PATH_SUCCESS';
export const FETCH_BROWSE_PATH_FAILED = 'FETCH_BROWSE_PATH_FAILED';
