export const FETCH_BROWSE_PATH = 'FETCH_BROWSE_PATH';
export const FETCH_HOME_PATH = 'FETCH_HOME_PATH';
export const FETCH_PATH_SUCCESS = 'FETCH_PATH_SUCCESS';
export const FETCH_PATH_FAILED = 'FETCH_PATH_FAILED';
export const SEARCH_PATH_REQUEST = 'SEARCH_PATH_REQUEST';
