export const FETCHING_USER = 'FETCHING_USER';
export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS';
export const FETCHING_USER_FAILURE = 'FETCHING_USER_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_REQUEST_SUCCESS = 'REGISTER_REQUEST_SUCCESS';
export const REGISTER_REQUEST_FAILURE = 'REGISTER_REQUEST_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'REGISTER_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'REGISTER_REQUEST_FAILURE';

export const LOGIN_FB_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FB_REQUEST_SUCCESS = 'LOGIN_FB_REQUEST_SUCCESS';
export const LOGIN_FB_REQUEST_FAILURE = 'LOGIN_FB_REQUEST_FAILURE';
