export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_REQUEST_SUCCESS = 'SIGNUP_REQUEST_SUCCESS';
export const SIGNUP_REQUEST_FAILURE = 'SIGNUP_REQUEST_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';

export const LOGIN_FB_REQUEST = 'LOGIN_FB_REQUEST';
export const LOGIN_FB_REQUEST_SUCCESS = 'LOGIN_FB_REQUEST_SUCCESS';
export const LOGIN_FB_REQUEST_FAILURE = 'LOGIN_FB_REQUEST_FAILURE';

export const AUTHORIZED = 'AUTHORIZED';
export const SIGN_OUT = 'SIGN_OUT';

export const CLEAR_ERROR = 'CLEAR_ERROR';
