export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_REQUEST_SUCCESS = 'SIGNUP_REQUEST_SUCCESS';
export const SIGNUP_REQUEST_FAILURE = 'SIGNUP_REQUEST_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';

export const LOGIN_FB_REQUEST = 'LOGIN_FB_REQUEST';
export const LOGIN_FB_REQUEST_SUCCESS = 'LOGIN_FB_REQUEST_SUCCESS';
export const LOGIN_FB_REQUEST_FAILURE = 'LOGIN_FB_REQUEST_FAILURE';

export const FETCH_PATH_REQUEST = 'FETCH_PATH_REQUEST';
export const FETCH_PATH_REQUEST_SUCCESS = 'FETCH_PATH_REQUEST_SUCCESS';
export const FETCH_PATH_REQUEST_FAILURE = 'FETCH_PATH_REQUEST_FAILURE';

export const FETCH_USERINFO_REQUEST = 'FETCH_USERINFO_REQUEST';
export const FETCH_USERINFO_REQUEST_SUCCESS = 'FETCH_USERINFO_REQUEST_SUCCESS';
export const FETCH_USERINFO_REQUEST_FAILURE = 'FETCH_USERINFO_REQUEST_FAILURE';

export const SAVE_USERINFO_REQUEST = 'SAVE_USERINFO_REQUEST';
export const SAVE_USERINFO_REQUEST_FAILURE = 'SAVE_USERINFO_REQUEST_FAILURE';

export const FETCH_QUIZ_REQUEST = 'FETCH_QUIZ_REQUEST';
export const FETCH_QUIZ_REQUEST_SUCCESS = 'FETCH_QUIZ_REQUEST_SUCCESS';
export const FETCH_QUIZ_REQUEST_FAILURE = 'FETCH_QUIZ_REQUEST_FAILURE';

export const SAVE_QUIZ_REQUEST = 'SAVE_QUIZ_REQUEST';
export const SAVE_QUIZ_REQUEST_SUCCESS = 'SAVE_QUIZ_REQUEST_SUCCESS';
export const SAVE_QUIZ_REQUEST_FAILURE = 'SAVE_QUIZ_REQUEST_FAILURE';

export const HIDE_LOADING_QUIZ = 'HIDE_LOADING_QUIZ';

export const AUTHORIZED = 'AUTHORIZED';
export const SIGN_OUT = 'SIGN_OUT';

export const CLEAR_ERROR = 'CLEAR_ERROR';
