export default {
  'Sign In': 'Sign In',
  'Signup / Login': 'Signup / Login',
  'Sign Out': 'Sign Out',
  'Hello {name}!': 'Hello {name}',
  'server_error': 'Have some errors, Please try again!',
  'popular': 'POPULAR',
  'lastest': 'LASTEST',
  'recommend': 'RECOMMEND',
  'vocals': 'VOCALS',
  'guitar': 'GUITAR',
  'overall progress': 'overall progress',
  'path enrollment': 'path enrollment',
  'lesson no video': 'This lesson currently has no video available',
  'view all path': 'View all paths',
  'sign_up_now': 'SIGN UP NOW',
  'take_quiz_again': 'TAKE QUIZ AGAIN',
  'discovery_now': 'DISCOVER NOW',
  'anonymous': 'Anonymous',
};
