export default {
  'Sign In': 'Đăng Nhập',
  'Signup / Login': 'Đăng ký / Đăng nhập',
  'Sign Out': 'Đăng Xuất',
  'Hello {name}!': 'Xin chào {name}!',
  'server_error': 'Có lỗi server, Làm phiền bạn thử vào lúc khác',
  'popular': 'POPULAR',
  'lastest': 'LASTEST',
  'recommend': 'RECOMMEND',
  'vocals': 'VOCALS',
  'guitar': 'GUITAR',
  'overall progress': 'Tiến độ',
  'path enrollment': 'Lịch sử học',
  'lesson no video': 'Bài học này hiện chưa có video',
  'view all path': 'Xem tất cả',
  'sign_up_now': 'Đăng Ký Đi M',
  'take_quiz_again': 'Làm Quiz Lại Đi M',
  'discovery_now': 'Khám Phá Đi M',
  'anonymous': 'Không tên',
};
